name: My First workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest 
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v6
          
        - name: Welcome message 
          run: echo "My first Github Action job"
        
        - name: List and Read files 
          run: |
             echo "ls My first Github Actions Job"
             ls -ltra
             cat README.md

        # - name: Read files
        #   run: cat README.md 



