name: timeout-test

on: 
    workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Build Docker image
        run: |
             echo Building Image
         
  deploy:
        timeout-minutes: 1
        runs-on: ubuntu-latest  
        steps:
        - name: Deploy Dummy JOB    
          run: |
            echo Deploying ....
            sleep 130